theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/biblio71.svg"
    footer: "/assets/images/biblio71.svg"
  # breadcrumb:
  #   position: after-hero
  summary:
    position: hero
  search:
    active: true